config/routes.rb
Rails.application.routes.draw do
  resources :milestones
  devise_for :users
  root 'milestones#index'

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    resources :milestones
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/milestone.rb
class Milestone < ApplicationRecord
  enum status: [:open, :secret]
  belongs_to :user
  validate :date_not_in_future, on: :create

  def date_not_in_future
    errors.add('error:', "Milestone date can't be in the future") if self.date > Date.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  include DeviseTokenAuth::Concerns::User
  has_many :milestones
  validates_uniqueness_of :username
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    protect_from_forgery with: :null_session
    include DeviseTokenAuth::Concerns::SetUserByToken
  end
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :null_session
    include DeviseTokenAuth::Concerns::SetUserByToken
  end
end

app/controllers/api/milestones_controller.rb
module Api
  class MilestonesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
    before_action :set_milestone, only: [:edit, :update, :destroy]

    # GET /milestones
    def index
      if params['filter'].eql?('personal') && user_signed_in?
        @milestones = current_user.milestones.includes(:user).order(date: :DESC, created_at: :DESC)
      else
        @milestones = Milestone.open.includes(:user).order(date: :DESC, created_at: :DESC)
      end
    end

    def create
      @milestone = current_user.milestones.new(milestone_params)

      if @milestone.save!
        render json: {message: "Your milestone created successfully."}
      else
        render json: {message: "something went wrong, please check your input"}
      end
    end

    # DELETE /milestones/1
    def destroy
      @milestone.destroy
      render json: {message: "Your milestone deleted successfully"}
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def milestone_params
      params.require(:milestone).permit(:title, :story, :date, :status)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, if: :verify_api
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def verify_api
    params[:controller].split('/')[0] != 'devise_token_auth'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_milestone, only: [:edit, :update, :destroy]

  # GET /milestones
  def index
    if params['filter'].eql?('personal') && user_signed_in?
      @milestones = current_user.milestones.includes(:user).order(date: :DESC, created_at: :DESC)
    else
      @milestones = Milestone.open.includes(:user).order(date: :DESC, created_at: :DESC)
    end
  end

  # GET /milestones/1
  def show
    redirect_to milestones_path(filter: 'personal')
  end

  # GET /milestones/new
  def new
    @milestone = current_user.milestones.new
  end

  # GET /milestones/1/edit
  def edit
  end

  # POST /milestones
  def create
    @milestone = current_user.milestones.new(milestone_params)

    if @milestone.save
      redirect_to milestones_path(filter: 'personal')
    else
      render :new
    end
  end

  # PATCH/PUT /milestones/1
  def update
    if @milestone.update(milestone_params)
      redirect_to @milestone, notice: 'Milestone was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /milestones/1
  def destroy
    @milestone.destroy
    redirect_to milestones_path(filter: 'personal'), notice: 'Milestone was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def milestone_params
      params.require(:milestone).permit(:title, :story, :date, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/layouts/_landing.html.erb
<header class="masthead bg-primary text-white text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="header-content mx-auto">

          <h1 class="mb-5">Save your milestones and share them with the world!</h1>
          <div class="badges">
            <a class="badge-link" target="_blank" href="https://play.google.com/store/apps/details?id=com.bernovia.mylestone"><%= image_tag 'google-play-badge.svg' %></a>
            <a class="badge-link"><%= image_tag 'app-store-badge.svg', style: 'opacity: 0.1;' %></a>
          </div>
        </div>
      </div>
        <div class="col-md-6">
          <div class="device-container">
            <div class="device-mockup iphone6_plus portrait white">
              <div class="device">
                <div class="screen">
                  <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                  <%= image_tag 'app.jpg', class: 'img-fluid' %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mylestone</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Save you milestones and share it with the world!">
  <meta name="author" content="Mohamad Alhaj Rahmoun">
  <meta name="author" content="Mohammed Mokresh">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Plugin CSS -->
  <link rel="stylesheet" href="/device-mockups/device-mockups.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body id="page-top">

  <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
    <div class="container">
      <% if user_signed_in? %>
        <%= link_to "Mylestone", milestones_path, class: 'navbar-brand js-scroll-trigger' %>
      <% else %>
        <%= link_to "Mylestone", root_path, class: 'navbar-brand js-scroll-trigger' %>
      <% end %>
      <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item mx-0 mx-lg-1">
            <%= link_to "Discover Milestones", milestones_path, class: 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item mx-0 mx-lg-1">
              <%= link_to "My Milestones", milestones_path(filter: 'personal'), class: 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <%= link_to "+New Milestone", new_milestone_path, class: 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %>
            </li>
          <% else %>
            <li class="nav-item mx-0 mx-lg-1">
              <%= link_to "Sign in", new_user_session_path, class: 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <%= link_to "Sign up", new_user_registration_path, class: 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <% if current_page?('/') %>
    <%= render 'layouts/landing'%>
  <% else %>
    <section class="bg-primary">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  <% end %>

  <div class="copyright py-4 text-center text-white">
    <div class="container">
      <div class="badges">
        <a class="badge-link-footer" target="_blank" href="https://play.google.com/store/apps/details?id=com.bernovia.mylestone"><%= image_tag 'google-play-badge.svg' %></a>
      </div>
      <small>A simple WebApp by <a style="color: #18bc9c;" target="_blank" href="https://github.com/mhdrahmoun">mhdrahmoun </a> | An Android App by <a style="color: #18bc9c;" target="_blank" href="https://github.com/MohammedMokresh">Mohammed Mokresh </a> | contact us: admin@mylestone.life </small>
    </div>
  </div>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
  <div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>
</body>
</html>

app/views/milestones/_form.html.erb
<style>
  .form-signin {
    max-width: 580px;
    padding: 15px;
    margin: 0 auto;
  }
  .form-signin .form-signin-heading,
  .form-signin .checkbox {
    margin-bottom: 10px;
  }
  .form-signin .checkbox {
    font-weight: normal;
  }
  .form-signin .form-control {
    position: relative;
    height: auto;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }
</style>

<%= form_with(model: milestone, local: true, html: {class: "form-signin" }) do |form| %>
  <% if milestone.errors.any? %>
    <div id="error_explanation">
      <h2 style="color: white"><%= pluralize(milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>
      <ul>
      <% milestone.errors.full_messages.each do |message| %>
        <li style="color: white"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title', maxlength: 40, required: true %>
  </div>

  <br>

  <div class="field">
    <div style="position: relative">
      <%= form.text_field :date, :class => 'form-control', id: 'datetimepicker4', placeholder: 'Date', required: true %>
    </div>
  </div>

  <br>

  <div class="field">
    <%= form.text_area :story, class: 'form-control', placeholder: 'Story', rows: 10, cols: 150, required: true %>
  </div>

  <br>

  <div class="field">
    <%= form.label :status, class: 'checkbox-text' do %>
      <%= form.check_box :status, {}, "secret", "open" %>
      Make it secret
    <% end %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Create Milestone", class: 'btn btn-lg btn-primary btn-block' %>
  </div>
<% end %>
<script>
    $(function () {
        $('#datetimepicker4').datetimepicker({
            format: 'L',
            format: 'YYYY-MM-DD'
        });
    });
</script>

app/views/milestones/edit.html.erb
<div class="text-center">
  <h1 class="heading-title">Update Milestone</h1>
</div>
<%= render 'form', milestone: @milestone %>

app/views/milestones/index.html.erb
<div class="text-center">
  <h3 class="heading-title">Latest Milestones</h3>
</div>
<div class="row">
    <div class="main-timeline #{@miles}">
      <% @milestones.each do |milestone| %>
        <div class="timeline">
          <div class="timeline-content">
            <span class="date">
              <span class="day"><%= milestone.date.day %><sup>th</sup></span>
              <span class="month"><%= milestone.date.strftime("%B")[0..2] %></span>
              <span class="year"><%= milestone.date.year %></span>
            </span>
            <h2 class="title"><%= milestone.title %> | by: <%= milestone.user.username %>
              <% if user_signed_in? && milestone.user_id.eql?(current_user.id) %>
                <%= link_to milestone_path(milestone), method: :delete, data: {confirm: 'Are you sure want to delete this milestone?'} do %>
                  | <%= icon('fas', 'trash') %></h2>
                <% end %>
                <% else %>
                </h2>
              <% end %>
            <p class="description"><%= milestone.story %></p>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/milestones/new.html.erb
<div class="text-center">
  <h1 class="heading-title">Create new Milestone</h1>
</div>
<%= render 'form', milestone: @milestone %>